version: '3.4'

services: 
  generator:
   build:
     context: .         
   image: aspnetcore/generator:multi
   ports:
    - "8083:80"
    
  mail:
    image: mailhog/mailhog
    ports:
     - "8025:8025"
     - "1025:1025"